// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe6xhpbcYPnMJTR0pXrqQ497bGrHw__L0',
    appId: '1:144252874688:web:1d9d568fe42c5c839aa225',
    messagingSenderId: '144252874688',
    projectId: 'parfimerija-2c006',
    authDomain: 'parfimerija-2c006.firebaseapp.com',
    storageBucket: 'parfimerija-2c006.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUraQnjiJn6mOO6AWYN-3gBvv0lT4Owz4',
    appId: '1:144252874688:android:53997b6cbf4770b49aa225',
    messagingSenderId: '144252874688',
    projectId: 'parfimerija-2c006',
    storageBucket: 'parfimerija-2c006.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVjYwbNz9i7nfPG3FP8GTZud0je3Yt4UE',
    appId: '1:144252874688:ios:55fc82acf235e4af9aa225',
    messagingSenderId: '144252874688',
    projectId: 'parfimerija-2c006',
    storageBucket: 'parfimerija-2c006.firebasestorage.app',
    iosBundleId: 'com.example.parfimerijaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVjYwbNz9i7nfPG3FP8GTZud0je3Yt4UE',
    appId: '1:144252874688:ios:55fc82acf235e4af9aa225',
    messagingSenderId: '144252874688',
    projectId: 'parfimerija-2c006',
    storageBucket: 'parfimerija-2c006.firebasestorage.app',
    iosBundleId: 'com.example.parfimerijaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe6xhpbcYPnMJTR0pXrqQ497bGrHw__L0',
    appId: '1:144252874688:web:888e27b5c78d53f79aa225',
    messagingSenderId: '144252874688',
    projectId: 'parfimerija-2c006',
    authDomain: 'parfimerija-2c006.firebaseapp.com',
    storageBucket: 'parfimerija-2c006.firebasestorage.app',
  );
}
